/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Enseignant;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.EnseignantService;

/**
 *
 * @author hp
 */
public class EnseignantForm extends javax.swing.JInternalFrame {
    private EnseignantService ens;
    private DefaultTableModel model;
    private static int id;
    

    /**
     * Creates new form EnseignantForm
     */
    public EnseignantForm() {
        initComponents();
        this.setTitle("Gestion des enseignants");
        ens = new EnseignantService();
        model = (DefaultTableModel) listeEnseignants.getModel();
        loadEnseignant();
        
    }
    void loadEnseignant(){
        model.setRowCount(0);
        for(Enseignant es :ens.findAll()){
            model.addRow(new Object[]{
            es.getId(),
            es.getNom(),
            es.getPrenom(),
            es.getMatiere()}
          );          
        }
        }
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationEnseignant = new javax.swing.JPanel();
        txtNomEns = new javax.swing.JTextField();
        txtPrenomEns = new javax.swing.JTextField();
        txtMatiereEns = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnAddEns = new javax.swing.JButton();
        bnDelete = new javax.swing.JButton();
        bnUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeEnseignants = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        informationEnseignant.setBackground(new java.awt.Color(124, 166, 166));
        informationEnseignant.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations des Enseignants", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14))); // NOI18N

        txtNomEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomEnsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-homme-prof-48.png"))); // NOI18N
        jLabel1.setText("Nom:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-homme-prof-48.png"))); // NOI18N
        jLabel2.setText("Prenom:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-courses-47.png"))); // NOI18N
        jLabel3.setText("Matiere:");

        bnAddEns.setBackground(new java.awt.Color(0, 102, 0));
        bnAddEns.setText("Ajouter");
        bnAddEns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnAddEnsActionPerformed(evt);
            }
        });

        bnDelete.setBackground(new java.awt.Color(255, 0, 0));
        bnDelete.setText("Supprimer");
        bnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDeleteActionPerformed(evt);
            }
        });

        bnUpdate.setBackground(new java.awt.Color(0, 0, 204));
        bnUpdate.setText("Modifier");
        bnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout informationEnseignantLayout = new javax.swing.GroupLayout(informationEnseignant);
        informationEnseignant.setLayout(informationEnseignantLayout);
        informationEnseignantLayout.setHorizontalGroup(
            informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationEnseignantLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomEns, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPrenomEns, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtMatiereEns, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
            .addGroup(informationEnseignantLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(bnAddEns, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(bnDelete)
                .addGap(114, 114, 114)
                .addComponent(bnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informationEnseignantLayout.setVerticalGroup(
            informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationEnseignantLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatiereEns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomEns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrenomEns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(informationEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnAddEns)
                    .addComponent(bnDelete)
                    .addComponent(bnUpdate))
                .addGap(25, 25, 25))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des enseignants", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 14))); // NOI18N

        listeEnseignants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prenom", "Matiere"
            }
        ));
        listeEnseignants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeEnseignantsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeEnseignants);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationEnseignant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomEnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomEnsActionPerformed

    private void bnAddEnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnAddEnsActionPerformed
        String nom = txtNomEns.getText().toString();
        String prenom = txtPrenomEns.getText().toString();
        String matiere = txtMatiereEns.getText().toString();
        if(ens.create(new Enseignant(id,nom, prenom, matiere))){
            JOptionPane.showMessageDialog(this, "Bien enregistré");
            loadEnseignant();
        }else {
            JOptionPane.showConfirmDialog(this, "Problème");
        }
    }//GEN-LAST:event_bnAddEnsActionPerformed

    private void listeEnseignantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeEnseignantsMouseClicked
       id = Integer.parseInt(model.getValueAt(listeEnseignants.getSelectedRow(), 0).toString());
      txtNomEns.setText(model.getValueAt(listeEnseignants.getSelectedRow(), 1).toString());
      txtPrenomEns.setText(model.getValueAt(listeEnseignants.getSelectedRow(), 2).toString());
      txtMatiereEns.setText(model.getValueAt(listeEnseignants.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_listeEnseignantsMouseClicked

    private void bnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDeleteActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer cette filière ?");
     if(response == 0){
         ens.delete(ens.findById(id));
         loadEnseignant();
     }
    }//GEN-LAST:event_bnDeleteActionPerformed

    private void bnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnUpdateActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment modifier cette filière ?");
     if(response == 0){ 
        String nom = txtNomEns.getText().toString();
        String prenom = txtPrenomEns.getText().toString();
        String matiere = txtMatiereEns.getText().toString();
        if(ens.update(new Enseignant(id,nom,prenom,matiere))){
            JOptionPane.showMessageDialog(this, "Bien enregistrée");
            loadEnseignant();
        }else {
            JOptionPane.showConfirmDialog(this, "Problème");
        }
     }
    }//GEN-LAST:event_bnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnAddEns;
    private javax.swing.JButton bnDelete;
    private javax.swing.JButton bnUpdate;
    private javax.swing.JPanel informationEnseignant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeEnseignants;
    private javax.swing.JTextField txtMatiereEns;
    private javax.swing.JTextField txtNomEns;
    private javax.swing.JTextField txtPrenomEns;
    // End of variables declaration//GEN-END:variables
}
