/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;

/**
 *
 * @author hp
 */
public class MDIApplication extends javax.swing.JFrame {
 private static MDIApplication instance;
    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion d' évaluation des enseignants");
        this.setExtendedState(MAXIMIZED_BOTH); 
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);// Maximized window

    }
  public static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        EtudiantMenuItem = new javax.swing.JMenuItem();
        EnseignantMenuItem = new javax.swing.JMenuItem();
        EvaluationMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        EvaluationParEnseignant = new javax.swing.JMenuItem();
        SearchEnseignant = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        EtudiantMenuItem.setMnemonic('o');
        EtudiantMenuItem.setText("Etudiant");
        EtudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(EtudiantMenuItem);

        EnseignantMenuItem.setMnemonic('s');
        EnseignantMenuItem.setText("Enseignant");
        EnseignantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnseignantMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(EnseignantMenuItem);

        EvaluationMenuItem.setMnemonic('a');
        EvaluationMenuItem.setText("Evaluation");
        EvaluationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluationMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(EvaluationMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Rechreche");

        EvaluationParEnseignant.setMnemonic('t');
        EvaluationParEnseignant.setText("Evaluation par enseignant");
        EvaluationParEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluationParEnseignantActionPerformed(evt);
            }
        });
        editMenu.add(EvaluationParEnseignant);

        SearchEnseignant.setMnemonic('y');
        SearchEnseignant.setText("Enseignant");
        SearchEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEnseignantActionPerformed(evt);
            }
        });
        editMenu.add(SearchEnseignant);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void centerInternalFrame(javax.swing.JInternalFrame frame) {
    int x = (desktopPane.getWidth() - frame.getWidth()) / 2;
    int y = (desktopPane.getHeight() - frame.getHeight()) / 2;
    frame.setLocation(x, y);
}
private void closeAllInternalFrames() {
    for (javax.swing.JInternalFrame frame : desktopPane.getAllFrames()) {
        frame.dispose();
    }
}

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void EtudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantMenuItemActionPerformed
       closeAllInternalFrames();
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);
        centerInternalFrame(ef);
    }//GEN-LAST:event_EtudiantMenuItemActionPerformed

    private void EnseignantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnseignantMenuItemActionPerformed
        closeAllInternalFrames();
        EnseignantForm enf = new EnseignantForm();
        desktopPane.add(enf);
        enf.setVisible(true);
        centerInternalFrame(enf);
    }//GEN-LAST:event_EnseignantMenuItemActionPerformed

    private void EvaluationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluationMenuItemActionPerformed
        closeAllInternalFrames();
        EvaluationForm ef = new EvaluationForm();
        desktopPane.add(ef);
        ef.setVisible(true);
        centerInternalFrame(ef);
    }//GEN-LAST:event_EvaluationMenuItemActionPerformed

    private void EvaluationParEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluationParEnseignantActionPerformed
        closeAllInternalFrames();
        EvaluationParEnseignant efe = new EvaluationParEnseignant();
        desktopPane.add(efe);
        efe.setVisible(true);
        centerInternalFrame(efe);

    }//GEN-LAST:event_EvaluationParEnseignantActionPerformed

    private void SearchEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchEnseignantActionPerformed
        closeAllInternalFrames();
        SearchEnseignant se = new SearchEnseignant();
        desktopPane.add(se);
        se.setVisible(true);
        centerInternalFrame(se);
    }//GEN-LAST:event_SearchEnseignantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EnseignantMenuItem;
    private javax.swing.JMenuItem EtudiantMenuItem;
    private javax.swing.JMenuItem EvaluationMenuItem;
    private javax.swing.JMenuItem EvaluationParEnseignant;
    private javax.swing.JMenuItem SearchEnseignant;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    
    

}
